[2022-10-17 00:36:18,764] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-10-17 00:43:31,483] WARNING [django.request.log_response:241] Unauthorized: /django-async/
[2022-10-17 00:44:05,072] ERROR [django.request.log_response:241] Internal Server Error: /django-async/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'coroutine'>`
[2022-10-17 00:45:55,052] ERROR [django.request.log_response:241] Internal Server Error: /django-async/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'coroutine'>`
[2022-10-17 00:50:45,289] WARNING [django.security.csrf.log_response:241] Forbidden (CSRF cookie not set.): /django-async/
[2022-10-17 09:41:12,100] WARNING [django.request.log_response:241] Not Found: /diseases/
[2022-10-17 09:42:07,945] WARNING [django.request.log_response:241] Unauthorized: /diseases/
[2022-10-17 09:42:19,155] WARNING [django.request.log_response:241] Unauthorized: /diseases/
[2022-10-17 10:05:55,069] WARNING [django.request.log_response:241] Not Found: /instructions-categories/
[2022-10-17 10:06:44,193] WARNING [django.request.log_response:241] Not Found: /instructions-categories/
[2022-10-17 10:06:45,360] WARNING [django.request.log_response:241] Not Found: /instructions-categories/
[2022-10-17 12:00:18,275] WARNING [django.request.log_response:241] Unauthorized: /diseases/
[2022-10-17 12:41:13,181] WARNING [django.request.log_response:241] Bad Request: /diseases/
[2022-10-17 12:41:21,829] ERROR [django.request.log_response:241] Internal Server Error: /diseases/
[2022-10-17 12:41:50,432] ERROR [shared.exception_handler.__handle_attribute_error:122] type object 'Q' has no attribute 'ADD'
[2022-10-17 12:41:50,434] ERROR [django.request.log_response:241] Internal Server Error: /diseases/
[2022-10-17 12:43:50,550] WARNING [django.request.log_response:241] Bad Request: /diseases/
[2022-10-17 12:52:53,042] WARNING [django.request.log_response:241] Unauthorized: /doctor/specialists/
[2022-10-17 12:53:08,695] WARNING [django.request.log_response:241] Unauthorized: /doctor/specialists/
