[2022-10-03 03:12:29,415] ERROR [django.request.log_response:241] Internal Server Error: /async/
[2022-10-03 03:41:11,875] ERROR [django.request.log_response:241] Internal Server Error: /doctor/5/packages/
[2022-10-03 04:03:33,957] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'add_job' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
[2022-10-03 04:16:15,578] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'add_job' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
[2022-10-03 04:17:31,959] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'update_job' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
[2022-10-03 04:20:56,678] ERROR [django.request.log_response:241] Internal Server Error: /async/
[2022-10-03 04:27:06,989] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'add_job' ((2003, "Can't connect to MySQL server on 'capstone.czjd9ym4s3b2.ap-southeast-1.rds.amazonaws.com' (timed out)")). Retrying with a new DB connection...
[2022-10-03 04:30:48,556] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'update_job' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
[2022-10-03 10:12:54,302] WARNING [django.request.log_response:241] Unauthorized: /doctor/5/packages/
[2022-10-03 10:15:16,787] WARNING [django.request.log_response:241] Bad Request: /doctor/shifts/
[2022-10-03 19:03:41,572] WARNING [django.request.log_response:241] Unauthorized: /prescription/doctor/52/
[2022-10-03 19:10:20,441] WARNING [django.request.log_response:241] Not Found: /prescription-list/1
[2022-10-03 19:10:35,729] WARNING [django.request.log_response:241] Not Found: /prescription-list/1
[2022-10-03 19:11:20,055] ERROR [shared.exception_handler.__handle_attribute_error:122] 'QuerySet' object has no attribute 'pk'
[2022-10-03 19:11:20,057] ERROR [django.request.log_response:241] Internal Server Error: /prescription-list/doctor/1/
[2022-10-03 19:12:23,739] ERROR [django.request.log_response:241] Internal Server Error: /prescription-list/doctor/1/
[2022-10-03 19:13:18,833] ERROR [django.request.log_response:241] Internal Server Error: /prescription-list/doctor/1/
[2022-10-03 19:13:46,891] ERROR [django.request.log_response:241] Internal Server Error: /prescription-list/doctor/1/
[2022-10-03 19:14:27,047] ERROR [django.request.log_response:241] Internal Server Error: /prescription-list/doctor/1/
[2022-10-03 19:15:00,338] ERROR [django.request.log_response:241] Internal Server Error: /prescription-list/doctor/1/
[2022-10-03 19:19:18,394] ERROR [django.request.log_response:241] Internal Server Error: /prescription-list/doctor/1/
[2022-10-03 21:53:36,987] ERROR [django.request.log_response:241] Internal Server Error: /prescription-list/doctor/1/
[2022-10-03 03:12:29,415] ERROR [django.request.log_response:241] Internal Server Error: /async/
[2022-10-03 03:41:11,875] ERROR [django.request.log_response:241] Internal Server Error: /doctor/5/packages/
[2022-10-03 04:03:33,957] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'add_job' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
[2022-10-03 04:16:15,578] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'add_job' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
[2022-10-03 04:17:31,959] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'update_job' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
[2022-10-03 04:20:56,678] ERROR [django.request.log_response:241] Internal Server Error: /async/
[2022-10-03 04:27:06,989] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'add_job' ((2003, "Can't connect to MySQL server on 'capstone.czjd9ym4s3b2.ap-southeast-1.rds.amazonaws.com' (timed out)")). Retrying with a new DB connection...
[2022-10-03 04:30:48,556] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'update_job' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
[2022-10-03 10:12:54,302] WARNING [django.request.log_response:241] Unauthorized: /doctor/5/packages/
[2022-10-03 10:15:16,787] WARNING [django.request.log_response:241] Bad Request: /doctor/shifts/
