[2022-10-05 18:40:38,238] ERROR [django.request.log_response:241] Internal Server Error: /doctor/action/instruction/
[2022-10-05 18:46:04,904] WARNING [django.request.log_response:241] Not Found: /doctor/instruction/1
[2022-10-05 18:47:26,563] WARNING [django.request.log_response:241] Not Found: /doctor/instruction/1
[2022-10-05 18:48:03,069] WARNING [django.request.log_response:241] Unauthorized: /doctor/instruction/1
[2022-10-05 18:48:11,720] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1
[2022-10-05 18:50:45,422] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1
[2022-10-05 18:52:00,247] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1/
[2022-10-05 18:53:35,447] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1/
[2022-10-05 18:56:11,788] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1/
[2022-10-05 18:57:07,031] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1/
[2022-10-05 18:57:48,627] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1/
[2022-10-05 18:59:14,034] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1/
[2022-10-05 18:59:50,904] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1/
[2022-10-05 19:01:31,828] ERROR [shared.exception_handler.__handle_attribute_error:122] 'NoneType' object has no attribute 'name'
[2022-10-05 19:01:31,831] ERROR [django.request.log_response:241] Internal Server Error: /doctor/instruction/1/
[2022-10-05 19:48:49,422] ERROR [shared.exception_handler.__handle_attribute_error:122] Cannot find 'patient' on PrescriptionDetail object, 'patient' is an invalid parameter to prefetch_related()
[2022-10-05 19:48:49,426] ERROR [django.request.log_response:241] Internal Server Error: /health-records/1/
[2022-10-05 19:55:12,369] ERROR [shared.exception_handler.__handle_attribute_error:122] Cannot find 'medicalinstruction_set' on HealthRecord object, 'medicalinstruction_set' is an invalid parameter to prefetch_related()
[2022-10-05 19:55:12,371] ERROR [django.request.log_response:241] Internal Server Error: /health-records/1/
[2022-10-05 19:56:40,082] ERROR [shared.exception_handler.__handle_attribute_error:122] Cannot find 'medicalinstruction_set' on HealthRecord object, 'medicalinstruction_set' is an invalid parameter to prefetch_related()
[2022-10-05 19:56:40,086] ERROR [django.request.log_response:241] Internal Server Error: /health-records/1/
[2022-10-05 20:15:10,768] ERROR [shared.exception_handler.__handle_attribute_error:122] Cannot find 'instruction_medicalinstruction_set' on HealthRecord object, 'instruction_medicalinstruction_set' is an invalid parameter to prefetch_related()
[2022-10-05 20:15:10,773] ERROR [django.request.log_response:241] Internal Server Error: /health-records/1/
[2022-10-05 21:35:04,352] WARNING [django.request.log_response:241] Bad Request: /prescription/
[2022-10-05 21:35:53,624] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
Traceback (most recent call last):
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "E:\Enviroment\python\version3\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "E:\Enviroment\python\version3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Doctor is not JSON serializable
[2022-10-05 21:45:22,642] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 21:49:04,530] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:14:39,863] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:15:08,297] WARNING [django.request.log_response:241] Bad Request: /prescription/
[2022-10-05 22:17:54,262] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:19:27,874] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:22:22,438] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:23:44,085] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:24:24,213] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:24:58,461] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:28:25,430] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:34:23,293] ERROR [shared.exception_handler.__handle_attribute_error:122] 'tuple' object has no attribute 'save'
[2022-10-05 22:34:23,297] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:37:19,061] ERROR [shared.exception_handler.__handle_attribute_error:122] 'tuple' object has no attribute 'save'
[2022-10-05 22:37:19,064] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:41:14,560] ERROR [shared.exception_handler.__handle_attribute_error:122] 'tuple' object has no attribute 'save'
[2022-10-05 22:41:14,562] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:41:44,297] ERROR [shared.exception_handler.__handle_attribute_error:122] 'tuple' object has no attribute 'save'
[2022-10-05 22:41:44,298] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:43:22,418] ERROR [shared.exception_handler.__handle_attribute_error:122] 'tuple' object has no attribute 'save'
[2022-10-05 22:43:22,423] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:48:52,145] ERROR [shared.exception_handler.__handle_attribute_error:122] 'tuple' object has no attribute 'save'
[2022-10-05 22:48:52,152] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:49:19,605] ERROR [shared.exception_handler.__handle_attribute_error:122] 'tuple' object has no attribute 'save'
[2022-10-05 22:49:19,608] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:49:54,295] ERROR [shared.exception_handler.__handle_attribute_error:122] 'tuple' object has no attribute 'save'
[2022-10-05 22:49:54,300] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:50:15,637] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:51:17,148] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:52:09,227] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:54:19,490] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:55:12,943] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:57:36,326] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 22:58:17,715] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 23:07:45,884] WARNING [django.request.log_response:241] Bad Request: /prescription/
[2022-10-05 23:23:00,283] WARNING [django.request.log_response:241] Unauthorized: /prescription/
[2022-10-05 23:35:27,141] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 23:40:49,176] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
Traceback (most recent call last):
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "E:\Enviroment\python\version3\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "E:\Enviroment\python\version3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PrescriptionDetailListSerializer is not JSON serializable
[2022-10-05 23:41:45,857] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
Traceback (most recent call last):
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "E:\Enviroment\python\version3\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "E:\Enviroment\python\version3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PrescriptionDetailListSerializer is not JSON serializable
[2022-10-05 23:43:06,243] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
Traceback (most recent call last):
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "E:\Enviroment\python\version3\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "E:\Enviroment\python\version3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PrescriptionDetailListSerializer is not JSON serializable
[2022-10-05 23:44:31,923] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
Traceback (most recent call last):
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "E:\Enviroment\python\version3\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "E:\Enviroment\python\version3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PrescriptionDetailListSerializer is not JSON serializable
[2022-10-05 23:45:29,090] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 23:47:32,535] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 23:50:03,892] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
Traceback (most recent call last):
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\Enviroment\python\version3\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "E:\Enviroment\python\version3\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "E:\Enviroment\python\version3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\Enviroment\python\version3\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "E:\Enviroment\python\version3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PrescriptionDetailListSerializer is not JSON serializable
[2022-10-05 23:51:25,573] ERROR [shared.exception_handler.__handle_attribute_error:122] 'PrescriptionDetail' object has no attribute 'usage'
[2022-10-05 23:51:25,576] ERROR [django.request.log_response:241] Internal Server Error: /prescription/
[2022-10-05 15:02:17,142] WARNING [django.request.log_response:241] Unauthorized: /health-records/1/
