[2022-10-08 05:39:26,527] ERROR [shared.exception_handler.__handle_attribute_error:122] 'Schedule' object has no attribute '_add_hints'
[2022-10-08 05:39:26,531] ERROR [django.request.log_response:241] Internal Server Error: /user/me/appointments/history/
[2022-10-08 05:40:08,229] ERROR [shared.exception_handler.__handle_attribute_error:122] 'Schedule' object has no attribute '_add_hints'
[2022-10-08 05:40:08,233] ERROR [django.request.log_response:241] Internal Server Error: /user/me/appointments/history/
[2022-10-08 05:43:48,578] ERROR [shared.exception_handler.__handle_attribute_error:122] 'Schedule' object has no attribute '_add_hints'
[2022-10-08 05:43:48,582] ERROR [django.request.log_response:241] Internal Server Error: /user/me/appointments/history/
[2022-10-08 05:48:03,813] ERROR [django.request.log_response:241] Internal Server Error: /appointments/1/
[2022-10-08 06:27:40,579] ERROR [django.request.log_response:241] Internal Server Error: /user/me/agora-token/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/rest_framework/response.py", line 55, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
AssertionError: .accepted_renderer not set on Response
[2022-10-08 06:29:59,265] ERROR [django.request.log_response:241] Internal Server Error: /user/me/agora-token/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 494, in dispatch
    self.headers = self.default_response_headers  # deprecate?
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 158, in default_response_headers
    if len(self.renderer_classes) > 1:
TypeError: object of type 'type' has no len()
[2022-10-08 07:14:27,880] WARNING [django.request.log_response:241] Forbidden: /doctor/health-records/
[2022-10-08 07:14:44,359] WARNING [django.request.log_response:241] Bad Request: /doctor/health-records/
[2022-10-08 07:15:05,119] WARNING [django.request.log_response:241] Bad Request: /doctor/health-records/
